name: Test dot and apps on Fedora

on:
  workflow_dispatch:

jobs:
  test-dot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gbraad-actions/fedora:stable
      options: --privileged

    steps:
      - name: Requirement for dot
        run: |
          sudo dnf install -y zsh

      - name: Run dot command - apps codium install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps codium install

      - name: Run dot command - apps distrobox install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps distrobox install

      - name: Run apps command - install code
        uses: gbraad-dotfiles/apps-action@main
        with:
          appname: code
          action: install
