name: Test devbox

on:
  workflow_dispatch:

jobs:
  test-devbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: gbraad-dotfiles/install-action@main
        with:
          sudo-change-shell: true
        
      - name: Run devbox command - os-release
        id: devenv
        uses: gbraad-dotfiles/devbox-action@main
        with:
          prefix: fedora
          command: exec
          args: cat /etc/os-release

      - name: Run devbox command - systemctl
        uses: gbraad-dotfiles/devbox-action@main
        with: 
          prefix: ${{ steps.devenv.outputs.prefix }}
          command: exec
          args: systemctl status --no-pager

      - name: Run devenv command - stop
        uses: gbraad-dotfiles/devbox-action@main
        with: 
          prefix: ${{ steps.devenv.outputs.prefix }}
          command: stop
