name: Test on container image

on:
  workflow_dispatch:
    inputs:
      dot_user:
        description: 'User for dot-action'
        required: true
        default: 'gbraad'
      image:
        description: 'Image to run'
        required: true
        default: 'ghcr.io/gbraad-dotfiles/fedora:latest'

jobs:
  test-dot:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.image }}
      options: --privileged

    steps:
      - name: Run dot command - dotup
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            dotup
          as_user: ${{ github.event.inputs.dot_user }}

      - name: Run dot command - apps codium install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps codium install
          as_user: ${{ github.event.inputs.dot_user }}

      - name: Run dot command - apps distrobox install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps distrobox install
          as_user: ${{ github.event.inputs.dot_user }}

      # Expected to fail, as dotfiles NOT installed
      # Todo: add an 'as_user' option to the action
      #- name: Run apps command - install code
      #  uses: gbraad-dotfiles/apps-action@main
      #  with:
      #    appname: code
      #    action: install
