name: Test dot

on:
  workflow_dispatch:

jobs:
  test-dot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gbraad-actions/fedora:stable
      options: --privileged

    steps:
      - name: Requirement for dot
        run: |
          sudo dnf install -y zsh

      - name: Run dot command - apps codium install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps codium install

      - name: Run dot command - apps distrobox install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps distrobox install

      - name: Run dot command - devenv dotfedora exec cat /etc/os-release
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devenv dotfedora exec cat /etc/os-release

      - name: Run dot command - devbox fedora start
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devbox fedora start

      - name: Run dot command - devbox fedora exec cat /etc/os-release
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devbox fedora exec cat /etc/os-release

      - name: Run dot command - apps tailscale
        if: ${{ failure() }}
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps tailscale install
            apps tailscale config operator
            apps tailscale up
            # ssh needs to be set after going up
            apps tailscale config ssh
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Hang around
        if: ${{ failure() }}
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh runner@${IP}\` or \`dotscreen runner@${IP}\`"
          sleep infinity
