name: Test dot

on:
  workflow_dispatch:

jobs:
  test-dot:
    runs-on: ubuntu-latest
    steps:
      - name: Requiremnent for dot
        run: |
          sudo apt update
          sudo apt install -y zsh

      - name: Run dot command - apps codium install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps codium install

      - name: Run dot command - devenv dotfedora exec cat /etc/os-release
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devenv dotfedora exec cat /etc/os-release

