name: Test apps

on:
  workflow_dispatch:

jobs:
  test-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: gbraad-dotfiles/install-action@main
        
      - name: Run apps command - install code
        uses: gbraad-dotfiles/apps-action@main
        with:
          appname: code
          action: install

      - name: Run apps command - run servewb
        uses: gbraad-dotfiles/apps-action@main
        with: 
          appname: code
          action: serveweb
          args: --background
