name: Test dot

on:
  workflow_dispatch:

jobs:
  test-dot:
    runs-on: ubuntu-latest
    steps:
      - name: Requiremnent for dot
        run: |
          sudo apt update
          sudo apt install -y zsh

      - name: Run dot command - apps tailscale
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps tailscale install
            apps tailscale config operator
            apps tailscale config ssh
            apps tailscale up
            tailscale ip -4
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run dot command - apps codium install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps codium install

      - name: Run dot command - apps distrobox install
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            apps distrobox install

      - name: Run dot command - dotfiles switch
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            dotfiles switch

      - name: Run dot command - devenv dotfedora exec cat /etc/os-release
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devenv dotfedora exec cat /etc/os-release

      - name: Run dot command - devbox fedora start
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devbox fedora start

      - name: Run dot command - devbox fedora exec cat /etc/os-release
        uses: gbraad-dotfiles/dot-action@main
        with:
          run: |
            devbox fedora exec cat /etc/os-release

      - name: Hang around
        if: ${{ always() }}
        run: |
          sleep infinity
